# Generated by Django 4.2 on 2024-02-29 02:35

import closet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='photo',
            field=models.ImageField(upload_to=closet.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoe', 'Shoe')], max_length=50),
        ),
    ]
