# Generated by Django 4.2 on 2024-03-10 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('closet', '0002_alter_clothing_photo_alter_clothing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
