# Generated by Django 4.2 on 2024-02-29 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outfits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0002_alter_clothing_photo_alter_clothing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=outfits.models.user_directory_path)),
                ('bottom', models.ForeignKey(limit_choices_to={'type': 'bottom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_bottoms', to='closet.clothing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(limit_choices_to={'type': 'shoe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_shoes', to='closet.clothing')),
                ('top', models.ForeignKey(limit_choices_to={'type': 'top'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_tops', to='closet.clothing')),
            ],
        ),
    ]
