# Generated by Django 4.2 on 2024-03-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_clothing_created_at'),
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='top',
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottoms',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'bottom'}, related_name='outfit_bottoms', to='closet.clothing'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'shoe'}, related_name='outfit_shoes', to='closet.clothing'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tops',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'top'}, related_name='outfit_tops', to='closet.clothing'),
        ),
    ]
