# Generated by Django 4.2 on 2024-03-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_clothing_created_at'),
        ('outfits', '0002_remove_outfit_bottom_remove_outfit_shoe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='bottoms',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='tops',
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(limit_choices_to={'type': 'bottom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_bottoms', to='closet.clothing'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoe',
            field=models.ForeignKey(limit_choices_to={'type': 'shoe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_shoes', to='closet.clothing'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(limit_choices_to={'type': 'top'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_tops', to='closet.clothing'),
        ),
    ]
